# Generated by Django 5.1 on 2024-08-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('testname', models.CharField(max_length=100)),
                ('addr', models.TextField()),
            ],
            options={
                'db_table': 'test_table',
            },
        ),
    ]
